"""Add quant and ml tables

Revision ID: 3db43e3de48b
Revises: 
Create Date: 2026-06-27 12:20:18.059741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db43e3de48b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('india_equity_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('series', sa.String(length=5), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_traded', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('traded_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('delivery_qty', sa.BigInteger(), nullable=True),
    sa.Column('delivery_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('week52_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('week52_low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', 'series', name='uq_india_equity_daily')
    )
    op.create_index(op.f('ix_india_equity_daily_date'), 'india_equity_daily', ['date'], unique=False)
    op.create_index(op.f('ix_india_equity_daily_id'), 'india_equity_daily', ['id'], unique=False)
    op.create_index(op.f('ix_india_equity_daily_symbol'), 'india_equity_daily', ['symbol'], unique=False)
    op.create_table('india_fo_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('instrument', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('option_type', sa.String(length=2), nullable=True),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('settle_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('traded_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('change_in_oi', sa.BigInteger(), nullable=True),
    sa.Column('market_lot', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', 'expiry_date', 'strike_price', 'option_type', 'instrument', name='uq_india_fo_daily')
    )
    op.create_index(op.f('ix_india_fo_daily_date'), 'india_fo_daily', ['date'], unique=False)
    op.create_index(op.f('ix_india_fo_daily_expiry_date'), 'india_fo_daily', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_india_fo_daily_id'), 'india_fo_daily', ['id'], unique=False)
    op.create_index(op.f('ix_india_fo_daily_symbol'), 'india_fo_daily', ['symbol'], unique=False)
    op.create_table('ml_model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('training_date', sa.Date(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('validation_auc', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version', name='uq_ml_model_registry')
    )
    op.create_index(op.f('ix_ml_model_registry_id'), 'ml_model_registry', ['id'], unique=False)
    op.create_table('option_suggestions_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('spot_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('suggestion_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strikes', sa.Text(), nullable=False),
    sa.Column('entry_trigger', sa.Text(), nullable=False),
    sa.Column('risk_reward', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('ppi', sa.Integer(), nullable=False),
    sa.Column('recorded_legs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_suggestions_history_id'), 'option_suggestions_history', ['id'], unique=False)
    op.create_index(op.f('ix_option_suggestions_history_ticker'), 'option_suggestions_history', ['ticker'], unique=False)
    op.create_index(op.f('ix_option_suggestions_history_timestamp'), 'option_suggestions_history', ['timestamp'], unique=False)
    op.create_table('waitlist_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_signups_email'), 'waitlist_signups', ['email'], unique=True)
    op.create_index(op.f('ix_waitlist_signups_id'), 'waitlist_signups', ['id'], unique=False)
    op.create_table('ml_feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('total_gex_normalized', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('net_gex_sign', sa.Integer(), nullable=True),
    sa.Column('gex_concentration', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('call_wall_distance', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('put_wall_distance', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('gamma_flip_distance', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('gex_zscore_30', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('put_call_oi_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('put_call_volume_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('bullish_sentiment_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notional_flow_skew', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('atm_iv', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('iv_skew_25d', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('iv_term_slope', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('realized_vs_implied', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('bid_ask_spread_zscore', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('intraday_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('rolling_return_30m', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('rolling_return_60m', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('vwap_deviation', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('spot_return_15m', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('minutes_to_close', sa.Integer(), nullable=True),
    sa.Column('session_half', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('volume_spike_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('oi_velocity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('charm_decay_rate', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('vanna_exposure', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('target_direction_45m', sa.Integer(), nullable=True),
    sa.Column('target_breach_up_45m', sa.Integer(), nullable=True),
    sa.Column('target_breach_down_45m', sa.Integer(), nullable=True),
    sa.Column('target_direction_1d', sa.Integer(), nullable=True),
    sa.Column('target_direction_3d', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['option_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'mode', name='uq_ml_feature_snapshots')
    )
    op.create_index(op.f('ix_ml_feature_snapshots_id'), 'ml_feature_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_ml_feature_snapshots_mode'), 'ml_feature_snapshots', ['mode'], unique=False)
    op.create_index(op.f('ix_ml_feature_snapshots_snapshot_id'), 'ml_feature_snapshots', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_ml_feature_snapshots_ticker'), 'ml_feature_snapshots', ['ticker'], unique=False)
    op.create_index(op.f('ix_ml_feature_snapshots_timestamp'), 'ml_feature_snapshots', ['timestamp'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('anomaly_drivers', sa.Text(), nullable=True),
    sa.Column('xgb_direction', sa.String(length=10), nullable=True),
    sa.Column('xgb_conviction', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('xgb_breach_up_prob', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('xgb_breach_down_prob', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('xgb_feature_importance', sa.Text(), nullable=True),
    sa.Column('tft_high_p50', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('tft_high_p90', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('tft_low_p50', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('tft_low_p10', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('tft_close_p50', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('confluence_signal', sa.String(length=20), nullable=True),
    sa.Column('suggested_strikes', sa.Text(), nullable=True),
    sa.Column('actual_direction', sa.Integer(), nullable=True),
    sa.Column('actual_high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('actual_low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('prediction_accuracy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['option_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_mode'), 'ml_predictions', ['mode'], unique=False)
    op.create_index(op.f('ix_ml_predictions_snapshot_id'), 'ml_predictions', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_ticker'), 'ml_predictions', ['ticker'], unique=False)
    op.create_index(op.f('ix_ml_predictions_timestamp'), 'ml_predictions', ['timestamp'], unique=False)
    op.alter_column('cot_positions', 'open_interest',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('cot_positions_ticker_report_date_key'), 'cot_positions', type_='unique')
    op.drop_index(op.f('idx_cot_positions_ticker_date'), table_name='cot_positions')
    op.create_index(op.f('ix_cot_positions_id'), 'cot_positions', ['id'], unique=False)
    op.create_index(op.f('ix_cot_positions_ticker'), 'cot_positions', ['ticker'], unique=False)
    op.create_unique_constraint('uq_cot_positions', 'cot_positions', ['ticker', 'report_date'])
    op.drop_constraint(op.f('daily_option_summary_ticker_trade_date_key'), 'daily_option_summary', type_='unique')
    op.create_index(op.f('ix_daily_option_summary_id'), 'daily_option_summary', ['id'], unique=False)
    op.create_index(op.f('ix_daily_option_summary_ticker'), 'daily_option_summary', ['ticker'], unique=False)
    op.create_unique_constraint('uq_daily_option_summary', 'daily_option_summary', ['ticker', 'trade_date'])
    op.drop_constraint(op.f('interest_rates_rate_key_key'), 'interest_rates', type_='unique')
    op.create_index(op.f('ix_interest_rates_id'), 'interest_rates', ['id'], unique=False)
    op.create_index(op.f('ix_interest_rates_rate_key'), 'interest_rates', ['rate_key'], unique=True)
    op.drop_index(op.f('idx_journal_trades_date'), table_name='journal_trades')
    op.drop_index(op.f('idx_journal_trades_ticker'), table_name='journal_trades')
    op.create_index(op.f('ix_journal_trades_ticker'), 'journal_trades', ['ticker'], unique=False)
    op.create_index(op.f('ix_journal_trades_trade_date'), 'journal_trades', ['trade_date'], unique=False)
    op.drop_index(op.f('idx_option_data_exp_strike_type'), table_name='option_data')
    op.drop_index(op.f('idx_option_data_expiration'), table_name='option_data')
    op.drop_index(op.f('idx_option_data_snapshot'), table_name='option_data')
    op.drop_index(op.f('idx_option_data_strike'), table_name='option_data')
    op.drop_index(op.f('idx_option_data_type'), table_name='option_data')
    op.create_index(op.f('ix_option_data_expiration'), 'option_data', ['expiration'], unique=False)
    op.create_index(op.f('ix_option_data_id'), 'option_data', ['id'], unique=False)
    op.create_index(op.f('ix_option_data_option_type'), 'option_data', ['option_type'], unique=False)
    op.create_index(op.f('ix_option_data_snapshot_id'), 'option_data', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_option_data_strike'), 'option_data', ['strike'], unique=False)
    op.drop_index(op.f('idx_snapshots_ticker'), table_name='option_snapshots')
    op.drop_index(op.f('idx_snapshots_ticker_timestamp'), table_name='option_snapshots')
    op.drop_index(op.f('idx_snapshots_timestamp'), table_name='option_snapshots')
    op.create_index(op.f('ix_option_snapshots_id'), 'option_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_option_snapshots_ticker'), 'option_snapshots', ['ticker'], unique=False)
    op.create_index(op.f('ix_option_snapshots_timestamp'), 'option_snapshots', ['timestamp'], unique=False)
    op.drop_index(op.f('idx_quant_forecasts_ticker_date'), table_name='quant_forecasts')
    op.drop_constraint(op.f('quant_forecasts_ticker_forecast_date_key'), 'quant_forecasts', type_='unique')
    op.create_index(op.f('ix_quant_forecasts_id'), 'quant_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_quant_forecasts_ticker'), 'quant_forecasts', ['ticker'], unique=False)
    op.create_unique_constraint('uq_quant_forecasts', 'quant_forecasts', ['ticker', 'forecast_date'])
    op.drop_index(op.f('idx_spot_history'), table_name='spot_price_history')
    op.drop_constraint(op.f('spot_price_history_ticker_timestamp_key'), 'spot_price_history', type_='unique')
    op.create_index(op.f('ix_spot_price_history_id'), 'spot_price_history', ['id'], unique=False)
    op.create_index(op.f('ix_spot_price_history_ticker'), 'spot_price_history', ['ticker'], unique=False)
    op.create_index(op.f('ix_spot_price_history_timestamp'), 'spot_price_history', ['timestamp'], unique=False)
    op.create_unique_constraint('uq_spot_price_history', 'spot_price_history', ['ticker', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_spot_price_history', 'spot_price_history', type_='unique')
    op.drop_index(op.f('ix_spot_price_history_timestamp'), table_name='spot_price_history')
    op.drop_index(op.f('ix_spot_price_history_ticker'), table_name='spot_price_history')
    op.drop_index(op.f('ix_spot_price_history_id'), table_name='spot_price_history')
    op.create_unique_constraint(op.f('spot_price_history_ticker_timestamp_key'), 'spot_price_history', ['ticker', 'timestamp'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_spot_history'), 'spot_price_history', ['ticker', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_constraint('uq_quant_forecasts', 'quant_forecasts', type_='unique')
    op.drop_index(op.f('ix_quant_forecasts_ticker'), table_name='quant_forecasts')
    op.drop_index(op.f('ix_quant_forecasts_id'), table_name='quant_forecasts')
    op.create_unique_constraint(op.f('quant_forecasts_ticker_forecast_date_key'), 'quant_forecasts', ['ticker', 'forecast_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_quant_forecasts_ticker_date'), 'quant_forecasts', ['ticker', sa.literal_column('forecast_date DESC')], unique=False)
    op.drop_index(op.f('ix_option_snapshots_timestamp'), table_name='option_snapshots')
    op.drop_index(op.f('ix_option_snapshots_ticker'), table_name='option_snapshots')
    op.drop_index(op.f('ix_option_snapshots_id'), table_name='option_snapshots')
    op.create_index(op.f('idx_snapshots_timestamp'), 'option_snapshots', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_snapshots_ticker_timestamp'), 'option_snapshots', ['ticker', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_snapshots_ticker'), 'option_snapshots', ['ticker'], unique=False)
    op.drop_index(op.f('ix_option_data_strike'), table_name='option_data')
    op.drop_index(op.f('ix_option_data_snapshot_id'), table_name='option_data')
    op.drop_index(op.f('ix_option_data_option_type'), table_name='option_data')
    op.drop_index(op.f('ix_option_data_id'), table_name='option_data')
    op.drop_index(op.f('ix_option_data_expiration'), table_name='option_data')
    op.create_index(op.f('idx_option_data_type'), 'option_data', ['option_type'], unique=False)
    op.create_index(op.f('idx_option_data_strike'), 'option_data', ['strike'], unique=False)
    op.create_index(op.f('idx_option_data_snapshot'), 'option_data', ['snapshot_id'], unique=False)
    op.create_index(op.f('idx_option_data_expiration'), 'option_data', ['expiration'], unique=False)
    op.create_index(op.f('idx_option_data_exp_strike_type'), 'option_data', ['expiration', 'strike', 'option_type'], unique=False)
    op.drop_index(op.f('ix_journal_trades_trade_date'), table_name='journal_trades')
    op.drop_index(op.f('ix_journal_trades_ticker'), table_name='journal_trades')
    op.create_index(op.f('idx_journal_trades_ticker'), 'journal_trades', ['ticker'], unique=False)
    op.create_index(op.f('idx_journal_trades_date'), 'journal_trades', [sa.literal_column('trade_date DESC')], unique=False)
    op.drop_index(op.f('ix_interest_rates_rate_key'), table_name='interest_rates')
    op.drop_index(op.f('ix_interest_rates_id'), table_name='interest_rates')
    op.create_unique_constraint(op.f('interest_rates_rate_key_key'), 'interest_rates', ['rate_key'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_daily_option_summary', 'daily_option_summary', type_='unique')
    op.drop_index(op.f('ix_daily_option_summary_ticker'), table_name='daily_option_summary')
    op.drop_index(op.f('ix_daily_option_summary_id'), table_name='daily_option_summary')
    op.create_unique_constraint(op.f('daily_option_summary_ticker_trade_date_key'), 'daily_option_summary', ['ticker', 'trade_date'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_cot_positions', 'cot_positions', type_='unique')
    op.drop_index(op.f('ix_cot_positions_ticker'), table_name='cot_positions')
    op.drop_index(op.f('ix_cot_positions_id'), table_name='cot_positions')
    op.create_index(op.f('idx_cot_positions_ticker_date'), 'cot_positions', ['ticker', sa.literal_column('report_date DESC')], unique=False)
    op.create_unique_constraint(op.f('cot_positions_ticker_report_date_key'), 'cot_positions', ['ticker', 'report_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('cot_positions', 'open_interest',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_ml_predictions_timestamp'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_ticker'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_snapshot_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_mode'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_ml_feature_snapshots_timestamp'), table_name='ml_feature_snapshots')
    op.drop_index(op.f('ix_ml_feature_snapshots_ticker'), table_name='ml_feature_snapshots')
    op.drop_index(op.f('ix_ml_feature_snapshots_snapshot_id'), table_name='ml_feature_snapshots')
    op.drop_index(op.f('ix_ml_feature_snapshots_mode'), table_name='ml_feature_snapshots')
    op.drop_index(op.f('ix_ml_feature_snapshots_id'), table_name='ml_feature_snapshots')
    op.drop_table('ml_feature_snapshots')
    op.drop_index(op.f('ix_waitlist_signups_id'), table_name='waitlist_signups')
    op.drop_index(op.f('ix_waitlist_signups_email'), table_name='waitlist_signups')
    op.drop_table('waitlist_signups')
    op.drop_index(op.f('ix_option_suggestions_history_timestamp'), table_name='option_suggestions_history')
    op.drop_index(op.f('ix_option_suggestions_history_ticker'), table_name='option_suggestions_history')
    op.drop_index(op.f('ix_option_suggestions_history_id'), table_name='option_suggestions_history')
    op.drop_table('option_suggestions_history')
    op.drop_index(op.f('ix_ml_model_registry_id'), table_name='ml_model_registry')
    op.drop_table('ml_model_registry')
    op.drop_index(op.f('ix_india_fo_daily_symbol'), table_name='india_fo_daily')
    op.drop_index(op.f('ix_india_fo_daily_id'), table_name='india_fo_daily')
    op.drop_index(op.f('ix_india_fo_daily_expiry_date'), table_name='india_fo_daily')
    op.drop_index(op.f('ix_india_fo_daily_date'), table_name='india_fo_daily')
    op.drop_table('india_fo_daily')
    op.drop_index(op.f('ix_india_equity_daily_symbol'), table_name='india_equity_daily')
    op.drop_index(op.f('ix_india_equity_daily_id'), table_name='india_equity_daily')
    op.drop_index(op.f('ix_india_equity_daily_date'), table_name='india_equity_daily')
    op.drop_table('india_equity_daily')
    # ### end Alembic commands ###
